[server]
headless = true
address = "0.0.0.0"
port = 5000
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = true

[theme]
primaryColor = "#0A84FF"
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1D1D1F"
font = "sans serif"

[browser]
gatherUsageStats = false

[runner]
fastReruns = true

[ui]
hideTopBar = true

[global]
developmentMode = false
showWarningOnDirectExecution = false