[server]
headless = true
address = "0.0.0.0"
port = 5000
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = true

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[browser]
gatherUsageStats = false

[runner]
fastReruns = true

[ui]
hideTopBar = true

[global]
developmentMode = false
disableWatchdogWarning = true
showWarningOnDirectExecution = false